# For local development only.
services:
  phalcon-8.2:
    container_name: phalcon-8.2
    hostname: phalcon-82
    build: docker/8.2
    working_dir: /srv
    links:
      - mysql
      - postgres
    volumes:
      - .:/srv

  phalcon-8.3:
    container_name: phalcon-8.3
    hostname: phalcon-83
    build: docker/8.3
    working_dir: /srv
    links:
      - mysql
      - postgres
    volumes:
      - .:/srv

  mysql:
    container_name: phalcon-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DATA_MYSQL_PASS}
      - MYSQL_USER=${DATA_MYSQL_USER}
      - MYSQL_DATABASE=${DATA_MYSQL_NAME}
      - MYSQL_PASSWORD=${DATA_MYSQL_PASS}

  postgres:
    container_name: phalcon-postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DATA_POSTGRES_PASS}
      - POSTGRES_USER=${DATA_POSTGRES_USER}
      - POSTGRES_DB=${DATA_POSTGRES_NAME}

  mongodb:
    container_name: phalcon-mongodb
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATA_MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATA_MONGODB_PASS}
      - MONGO_INITDB_DATABASE=${DATA_MONGODB_NAME}

  redis:
    container_name: phalcon-redis
    image: redis:6-alpine

  memcached:
    container_name: phalcon-memcached
    image: memcached:1.6-alpine
